#  python-build pipeline

##
#   SUPPLY SERVER
##

image: python:3.8

pipelines:
  branches:
    master:
      - step:
          name: Unit Test
          caches:
            - pip
          script:
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - pip install pytest
            - pytest -v test/* --junitxml=test-reports/report.xml
      - step:
          name: Test Coverage
          script:
            - coverage exclude -f
              - "*config.py"
            - coverage run -m pytest
            - coverage xml -o test-reports/coverage.xml
            - coverage report --fail-under=80
      # - step:
      #     name: Lint Code
      #     script:
      #       # Enforce style consistency across Python projects https://flake8.pycqa.org
      #       - pip install flake8
      #       - flake8 . --extend-exclude=dist,build --show-source --statistics
      - step:
          name: Deploy Code
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: $USER
                SERVER: $SUPPLY_SERVER
                COMMAND: '/home/team21/SupplyBackendDeployScript.sh'
